"""Default Tushare clean profile definitions."""

from __future__ import annotations

from quant_investor.market.tushare_cleaning_types import TushareCleanProfile


def get_default_tushare_clean_profiles() -> dict[str, TushareCleanProfile]:
    daily_numeric = [
        "open",
        "high",
        "low",
        "close",
        "pre_close",
        "change",
        "pct_chg",
        "vol",
        "amount",
        "adj_factor",
        "adj_open",
        "adj_high",
        "adj_low",
        "adj_close",
    ]
    return {
        "daily": TushareCleanProfile(
            table_name="daily",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date", "open", "high", "low", "close", "vol", "amount"],
            optional_columns=["pre_close", "change", "pct_chg", "adj_factor", "adj_open", "adj_high", "adj_low", "adj_close"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            numeric_columns=daily_numeric,
            positive_columns=["open", "high", "low", "close", "adj_factor", "adj_open", "adj_high", "adj_low", "adj_close"],
            non_negative_columns=["vol", "amount"],
            price_columns=["open", "high", "low", "close", "pre_close", "adj_open", "adj_high", "adj_low", "adj_close"],
            volume_columns=["vol"],
            amount_columns=["amount"],
            ohlc_columns={"open": "open", "high": "high", "low": "low", "close": "close"},
            factor_required_columns=["ts_code", "trade_date", "open", "high", "low", "close", "vol", "amount", "adj_factor"],
            model_optional_columns=["pre_close", "change", "pct_chg", "adj_open", "adj_high", "adj_low", "adj_close"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["ts_code"],
        ),
        "adj_factor": TushareCleanProfile(
            table_name="adj_factor",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date", "adj_factor"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            numeric_columns=["adj_factor"],
            positive_columns=["adj_factor"],
            factor_required_columns=["ts_code", "trade_date", "adj_factor"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["ts_code"],
        ),
        "daily_basic": TushareCleanProfile(
            table_name="daily_basic",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date"],
            optional_columns=["close", "turnover_rate", "volume_ratio", "pe", "pb", "total_mv", "circ_mv"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            numeric_columns=["close", "turnover_rate", "volume_ratio", "pe", "pb", "total_mv", "circ_mv"],
            positive_columns=["close"],
            factor_required_columns=["ts_code", "trade_date"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["ts_code"],
        ),
        "stock_basic": TushareCleanProfile(
            table_name="stock_basic",
            primary_key=["ts_code"],
            required_columns=["ts_code", "name"],
            optional_columns=["symbol", "area", "industry", "market", "list_date", "delist_date", "list_status"],
            date_columns=["list_date", "delist_date"],
            ts_code_columns=["ts_code"],
            factor_required_columns=["ts_code", "name"],
            point_in_time_columns=["list_date", "delist_date"],
            preferred_storage_format="csv",
        ),
        "suspend_d": TushareCleanProfile(
            table_name="suspend_d",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date"],
            optional_columns=["suspend_type"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            factor_required_columns=["ts_code", "trade_date"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="csv",
        ),
        "suspend": TushareCleanProfile(
            table_name="suspend",
            primary_key=["ts_code", "suspend_date"],
            required_columns=["ts_code", "suspend_date"],
            optional_columns=["resume_date", "ann_date", "suspend_reason", "reason_type"],
            date_columns=["suspend_date", "resume_date", "ann_date"],
            ts_code_columns=["ts_code"],
            factor_required_columns=["ts_code", "suspend_date"],
            point_in_time_columns=["ann_date", "suspend_date", "resume_date"],
            preferred_storage_format="csv",
        ),
        "stk_limit": TushareCleanProfile(
            table_name="stk_limit",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date", "up_limit", "down_limit"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            numeric_columns=["up_limit", "down_limit"],
            positive_columns=["up_limit", "down_limit"],
            price_columns=["up_limit", "down_limit"],
            factor_required_columns=["ts_code", "trade_date", "up_limit", "down_limit"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["ts_code"],
        ),
        "index_daily": TushareCleanProfile(
            table_name="index_daily",
            primary_key=["ts_code", "trade_date"],
            required_columns=["ts_code", "trade_date", "open", "high", "low", "close"],
            optional_columns=["pre_close", "change", "pct_chg", "vol", "amount"],
            date_columns=["trade_date"],
            ts_code_columns=["ts_code"],
            numeric_columns=["open", "high", "low", "close", "pre_close", "change", "pct_chg", "vol", "amount"],
            positive_columns=["open", "high", "low", "close"],
            non_negative_columns=["vol", "amount"],
            price_columns=["open", "high", "low", "close", "pre_close"],
            volume_columns=["vol"],
            amount_columns=["amount"],
            ohlc_columns={"open": "open", "high": "high", "low": "low", "close": "close"},
            factor_required_columns=["ts_code", "trade_date", "open", "high", "low", "close"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["ts_code"],
        ),
        "index_weight": TushareCleanProfile(
            table_name="index_weight",
            primary_key=["index_code", "con_code", "trade_date"],
            required_columns=["index_code", "con_code", "trade_date", "weight"],
            optional_columns=["trade_date"],
            date_columns=["trade_date"],
            ts_code_columns=["index_code", "con_code"],
            numeric_columns=["weight"],
            non_negative_columns=["weight"],
            factor_required_columns=["index_code", "con_code", "trade_date", "weight"],
            point_in_time_columns=["trade_date"],
            preferred_storage_format="dual",
            parquet_partition_columns=["index_code"],
        ),
        "trade_cal": TushareCleanProfile(
            table_name="trade_cal",
            primary_key=["cal_date"],
            required_columns=["cal_date", "is_open"],
            optional_columns=["exchange", "pretrade_date"],
            date_columns=["cal_date", "pretrade_date"],
            numeric_columns=["is_open"],
            factor_required_columns=["cal_date", "is_open"],
            point_in_time_columns=["cal_date"],
            preferred_storage_format="csv",
        ),
    }


__all__ = ["get_default_tushare_clean_profiles"]
