"""Strict, offline fundamental research protocol core."""

from .ledger import HashChainLedger, LedgerConflictError, validate_job_transition
from .models import (
    ApplicationEventV1,
    ApplicationState,
    ClaimKind,
    ClaimV1,
    Dimension,
    DimensionAssessmentV1,
    DimensionSignal,
    FundamentalOverlayV1,
    FundamentalResearchDossierV1,
    FundamentalResearchRequestV1,
    FundamentalResearchResponseV1,
    JobEventV1,
    JobState,
    LocalFundamentalContextV1,
    SourceEligibilityPolicyV1,
    SourceRecordV1,
    SourceTier,
    compute_base_score_sha256,
    compute_source_policy_sha256,
)
from .scoring import DIMENSION_WEIGHTS, build_overlay
from .runtime import ActivationManifestV1, RuntimeOverlayDecision, consume_overlay
from .governance import (
    ActivationGateEvidenceV2,
    CanonicalLongitudinalMetricV1,
    CanonicalNavSnapshotV1,
    HoldingsScopeSnapshotV1,
    LongitudinalObservationV1,
    LongitudinalOutcomeArtifactV1,
    LongitudinalSourceArtifactV1,
    activation_readiness,
    append_longitudinal_observation,
    build_activation_gate_evidence,
)
from .service import ResponseBindingError, import_response_files, validate_response
from .longitudinal_producer import (
    LongitudinalProducerError,
    produce_nav_attribution_observation,
    produce_target_weight_observation,
)
from .storage import atomic_write_json_model, load_json_model, model_sha256

__all__ = [
    "ApplicationEventV1",
    "ApplicationState",
    "ActivationGateEvidenceV2",
    "ActivationManifestV1",
    "CanonicalLongitudinalMetricV1",
    "CanonicalNavSnapshotV1",
    "HoldingsScopeSnapshotV1",
    "ClaimKind",
    "ClaimV1",
    "DIMENSION_WEIGHTS",
    "Dimension",
    "DimensionAssessmentV1",
    "DimensionSignal",
    "FundamentalOverlayV1",
    "FundamentalResearchDossierV1",
    "FundamentalResearchRequestV1",
    "FundamentalResearchResponseV1",
    "HashChainLedger",
    "JobEventV1",
    "JobState",
    "LongitudinalObservationV1",
    "LongitudinalOutcomeArtifactV1",
    "LongitudinalProducerError",
    "LongitudinalSourceArtifactV1",
    "LedgerConflictError",
    "LocalFundamentalContextV1",
    "ResponseBindingError",
    "RuntimeOverlayDecision",
    "SourceEligibilityPolicyV1",
    "SourceRecordV1",
    "SourceTier",
    "atomic_write_json_model",
    "activation_readiness",
    "append_longitudinal_observation",
    "build_overlay",
    "build_activation_gate_evidence",
    "consume_overlay",
    "compute_base_score_sha256",
    "compute_source_policy_sha256",
    "import_response_files",
    "load_json_model",
    "model_sha256",
    "produce_nav_attribution_observation",
    "produce_target_weight_observation",
    "validate_job_transition",
    "validate_response",
]
