"""Stable fail-closed errors for the unified-runtime cutover tooling."""

from __future__ import annotations

from typing import Final


class UnifiedCutoverError(RuntimeError):
    """A deterministic inventory or migration gate could not be closed."""

    def __init__(self, code: str, detail: str) -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}")


RULES_UNAVAILABLE: Final = "RULES_UNAVAILABLE"
RULES_NON_CANONICAL: Final = "RULES_NON_CANONICAL"
RULES_SCHEMA_INVALID: Final = "RULES_SCHEMA_INVALID"
TRACKED_ROOT_MISSING: Final = "TRACKED_ROOT_MISSING"
TRACKED_ROOT_COLLISION: Final = "TRACKED_ROOT_COLLISION"
RUNTIME_ROOT_COLLISION: Final = "RUNTIME_ROOT_COLLISION"
PATH_COLLISION: Final = "PATH_COLLISION"
SYMLINK_REFUSED: Final = "SYMLINK_REFUSED"
UNSAFE_PATH: Final = "UNSAFE_PATH"
UNSTABLE_FILE: Final = "UNSTABLE_FILE"
FILE_TOO_LARGE: Final = "FILE_TOO_LARGE"
UNPARSEABLE_PYTHON: Final = "UNPARSEABLE_PYTHON"
UNPARSEABLE_TOML: Final = "UNPARSEABLE_TOML"
UNPARSEABLE_YAML: Final = "UNPARSEABLE_YAML"
UNPARSEABLE_SHELL: Final = "UNPARSEABLE_SHELL"
UNPARSEABLE_JSON: Final = "UNPARSEABLE_JSON"
POINTER_FILENAME_UNAPPROVED: Final = "POINTER_FILENAME_UNAPPROVED"
BROKEN_REFERENCE: Final = "BROKEN_REFERENCE"
REFERENCE_HASH_MISMATCH: Final = "REFERENCE_HASH_MISMATCH"
REFERENCE_COLLISION: Final = "REFERENCE_COLLISION"
MODULE_COLLISION: Final = "MODULE_COLLISION"
BROKEN_LOCAL_IMPORT: Final = "BROKEN_LOCAL_IMPORT"
DYNAMIC_IMPORT_NOT_ALLOWLISTED: Final = "DYNAMIC_IMPORT_NOT_ALLOWLISTED"
DYNAMIC_IMPORT_ALLOWLIST_MISMATCH: Final = "DYNAMIC_IMPORT_ALLOWLIST_MISMATCH"
DYNAMIC_IMPORT_ALLOWLIST_UNUSED: Final = "DYNAMIC_IMPORT_ALLOWLIST_UNUSED"
LEGACY_SEED_MISMATCH: Final = "LEGACY_SEED_MISMATCH"
REPLACEMENT_TEST_MAP_INVALID: Final = "REPLACEMENT_TEST_MAP_INVALID"
UNRESOLVED_REPLACEMENT_TEST: Final = "UNRESOLVED_REPLACEMENT_TEST"
LEGACY_TEST_STILL_PRESENT: Final = "LEGACY_TEST_STILL_PRESENT"
REPLACEMENT_TEST_MISSING: Final = "REPLACEMENT_TEST_MISSING"
CLASSIFICATION_COLLISION: Final = "CLASSIFICATION_COLLISION"
UNCLASSIFIED_PATH: Final = "UNCLASSIFIED_PATH"
SOURCE_TARGET_COLLISION: Final = "SOURCE_TARGET_COLLISION"
ARCHIVE_PLAN_INVALID: Final = "ARCHIVE_PLAN_INVALID"
ARCHIVE_COPY_FORBIDDEN: Final = "ARCHIVE_COPY_FORBIDDEN"
ARCHIVE_COPY_CONFLICT: Final = "ARCHIVE_COPY_CONFLICT"
UNIFIED_ACTIVE_PRESENT: Final = "UNIFIED_ACTIVE_PRESENT"
PERMANENT_MARKER_PRESENT: Final = "PERMANENT_MARKER_PRESENT"
RECEIPT_CONFLICT: Final = "RECEIPT_CONFLICT"
RECEIPT_INVALID: Final = "RECEIPT_INVALID"


__all__ = ["UnifiedCutoverError"]
