"""Stable, versionless Factor governance public API.

All builders below are pure, hash-bound candidate or observation operations.
Only :mod:`quant_investor.system` can make a Factor set official by activating a
verified generation.
"""

from .admission import (
    ADMITTED_SET_KIND,
    EVALUATION_KIND,
    PROSPECTIVE_ADMISSION_ROUTE,
    validate_admitted_factor_set,
    validate_preregistration_evaluation,
)
from .bootstrap import (
    BLEND_W75_CONTROL,
    BLEND_W80,
    BOOTSTRAP_LANE,
    BOOTSTRAP_SET_KIND,
    CANONICAL_PARQUET,
    LOW_DOLLAR_VOLUME,
    NOT_CLAIMED,
    PROSPECTIVE_LANE,
    FactorSourceRole,
    bootstrap_factor_definitions,
    build_bootstrap_factor_set,
    compute_bootstrap_signals,
    derive_active_required_source_roles,
    required_source_roles_for_factor,
    validate_bootstrap_factor_set,
)
from .bootstrap_evidence import (
    BOOTSTRAP_ADMISSION_ROUTE,
    BOOTSTRAP_DECISION_SOURCE_ID,
    BOOTSTRAP_EVIDENCE_KIND,
    build_bootstrap_exception_evidence,
    validate_bootstrap_exception_evidence,
)
from .errors import FactorGovernanceError
from .custody import (
    COMPOSITE_STATE_KIND,
    CUSTODY_RECORD_KIND,
    validate_composite_state,
    validate_custody_record,
)
from .contextual import CONTEXTUAL_RESULT_KIND, validate_contextual_result
from .execution import (
    EXECUTION_EVIDENCE_KIND,
    validate_execution_turnover_evidence,
)
from .lifecycle import (
    ACTIVE,
    INSUFFICIENT_EVIDENCE,
    LIFECYCLE_AUTHORITY,
    LIFECYCLE_DECISION_KIND,
    LIFECYCLE_POLICY_ID,
    LIFECYCLE_POLICY_KIND,
    PREREGISTERED,
    PROBATION,
    RETIRED,
    SOURCE_BLOCKED,
    WATCH,
    build_lifecycle_decision,
    build_lifecycle_policy_v1,
    production_eligible,
    propose_lifecycle_weights,
    transition_lifecycle_state,
    validate_lifecycle_decision,
    validate_lifecycle_policy,
    weight_scale_for_state,
)
from .lineage import (
    OBSERVATION_HEAD_KIND,
    append_observation_cas,
    read_observation_head,
    validate_observation_head,
)
from .manifest import VALIDATOR_MANIFEST_KIND, validate_validator_manifest
from .prospective import (
    OBSERVATION_KIND,
    PREREGISTRATION_KIND,
    SELECTION_KIND,
    SIGNAL_CAPTURE_KIND,
    validate_configuration_selection,
    validate_observation,
    validate_preregistration,
    validate_signal_capture,
)
from .receipt import (
    VALIDATION_RECEIPT_KIND,
    validate_factor_validation_receipt,
)
from .source import SOURCE_DECODE_ATTESTATION_KIND, validate_source_decode_attestation
from .status import (
    FACTOR_BLOCKED,
    FACTOR_READY,
    FACTOR_STATUS_KIND,
    validate_factor_status,
)
from .store import (
    BootstrapClosure,
    FactorValidationStore,
    bootstrap_validation_namespace_id,
    prospective_validation_namespace_id,
)

__all__ = [
    "ACTIVE",
    "ADMITTED_SET_KIND",
    "BLEND_W75_CONTROL",
    "BLEND_W80",
    "BOOTSTRAP_ADMISSION_ROUTE",
    "BOOTSTRAP_DECISION_SOURCE_ID",
    "BOOTSTRAP_EVIDENCE_KIND",
    "BOOTSTRAP_LANE",
    "BOOTSTRAP_SET_KIND",
    "BootstrapClosure",
    "CANONICAL_PARQUET",
    "COMPOSITE_STATE_KIND",
    "CONTEXTUAL_RESULT_KIND",
    "CUSTODY_RECORD_KIND",
    "EVALUATION_KIND",
    "EXECUTION_EVIDENCE_KIND",
    "FACTOR_BLOCKED",
    "FACTOR_READY",
    "FACTOR_STATUS_KIND",
    "FactorGovernanceError",
    "FactorValidationStore",
    "FactorSourceRole",
    "INSUFFICIENT_EVIDENCE",
    "LIFECYCLE_AUTHORITY",
    "LIFECYCLE_DECISION_KIND",
    "LIFECYCLE_POLICY_ID",
    "LIFECYCLE_POLICY_KIND",
    "LOW_DOLLAR_VOLUME",
    "NOT_CLAIMED",
    "OBSERVATION_KIND",
    "OBSERVATION_HEAD_KIND",
    "PREREGISTERED",
    "PREREGISTRATION_KIND",
    "PROBATION",
    "PROSPECTIVE_ADMISSION_ROUTE",
    "PROSPECTIVE_LANE",
    "RETIRED",
    "SELECTION_KIND",
    "SIGNAL_CAPTURE_KIND",
    "SOURCE_BLOCKED",
    "SOURCE_DECODE_ATTESTATION_KIND",
    "VALIDATION_RECEIPT_KIND",
    "VALIDATOR_MANIFEST_KIND",
    "WATCH",
    "bootstrap_factor_definitions",
    "bootstrap_validation_namespace_id",
    "append_observation_cas",
    "build_bootstrap_exception_evidence",
    "build_bootstrap_factor_set",
    "build_lifecycle_decision",
    "build_lifecycle_policy_v1",
    "compute_bootstrap_signals",
    "derive_active_required_source_roles",
    "production_eligible",
    "propose_lifecycle_weights",
    "read_observation_head",
    "required_source_roles_for_factor",
    "prospective_validation_namespace_id",
    "transition_lifecycle_state",
    "validate_admitted_factor_set",
    "validate_bootstrap_exception_evidence",
    "validate_bootstrap_factor_set",
    "validate_configuration_selection",
    "validate_contextual_result",
    "validate_composite_state",
    "validate_custody_record",
    "validate_factor_status",
    "validate_factor_validation_receipt",
    "validate_lifecycle_decision",
    "validate_lifecycle_policy",
    "validate_validator_manifest",
    "validate_execution_turnover_evidence",
    "validate_observation",
    "validate_observation_head",
    "validate_preregistration",
    "validate_preregistration_evaluation",
    "validate_signal_capture",
    "validate_source_decode_attestation",
    "weight_scale_for_state",
]
