from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import os
import stat
import struct
import subprocess
from pathlib import Path
from typing import Any, Callable

import pytest

from quant_investor.v17_v2_contract.schema_validation import (
    SchemaValidationError,
    preflight_packaged_schema,
    validate_instance_against_schema,
)

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "v17_offline_dependency_evidence.py"
SCHEMA = ROOT / "scripts" / "schemas" / "v17_offline_dependency_evidence.v2.schema.json"
SPEC = importlib.util.spec_from_file_location("v17_offline_dependency_evidence", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
subject = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(subject)

SHA = "0" * 64


def _export(*requirements: str) -> bytes:
    lines = [
        "# This file was autogenerated by uv via the following command:",
        "#    uv export --frozen --no-hashes --no-emit-project",
        *requirements,
    ]
    return ("\n".join(lines) + "\n").encode()


def _metadata_record(name: str, version: str) -> dict[str, object]:
    raw = f"Name: {name}\nVersion: {version}\n".encode()
    return {
        "name": name,
        "version": version,
        "metadata_sha256": hashlib.sha256(raw).hexdigest(),
        "metadata_size": len(raw),
    }


def _selected(filename: str, raw: bytes, *, tags: list[str]) -> dict[str, object]:
    return {
        "kind": "wheel",
        "filename": filename,
        "url": f"https://files.pythonhosted.org/packages/{filename}",
        "sha256": hashlib.sha256(raw).hexdigest(),
        "size": len(raw),
        "tags": tags,
    }


def _source() -> dict[str, object]:
    return {
        "base_commit": "0" * 40,
        "source_state_sha256": SHA,
        "porcelain_sha256": SHA,
        "binary_diff_sha256": SHA,
        "untracked_inventory_sha256": SHA,
    }


def _toolchain() -> dict[str, object]:
    return {
        "base_python": {
            "lexical_path": subject.BASE_PYTHON_PATH,
            "realpath": subject.BASE_PYTHON_PATH,
            "sha256": subject.BASE_PYTHON_SHA256,
            "size_bytes": subject.BASE_PYTHON_SIZE,
            "mode": "0755",
            "executable": True,
            "implementation": "cpython",
            "version": "3.13.7",
            "version_info": [3, 13, 7],
        },
        "uv": {
            "lexical_path": subject.UV_PATH,
            "realpath": subject.UV_PATH,
            "sha256": subject.UV_SHA256,
            "size_bytes": subject.UV_SIZE,
            "mode": "0755",
            "executable": True,
            "version": "0.10.9",
            "output": subject.UV_VERSION_OUTPUT,
        },
        "uv_cache": {
            "path": subject.UV_CACHE_PATH,
            "realpath": subject.UV_CACHE_PATH,
            "st_dev": 1,
            "st_ino": 2,
            "uid": os.getuid(),
            "mode": "0755",
        },
        "pip_scope": copy.deepcopy(subject.PIP_SCOPE),
    }


def _native_environment(work_root: Path, target_venv: Path) -> dict[str, str]:
    return {
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTHONHASHSEED": "0",
        "PYTHONNOUSERSITE": "1",
        "PIP_CONFIG_FILE": "/dev/null",
        "PIP_DISABLE_PIP_VERSION_CHECK": "1",
        "PIP_NO_INDEX": "1",
        "PIP_NO_INPUT": "1",
        "UV_CACHE_DIR": subject.UV_CACHE_PATH,
        "UV_NO_CONFIG": "1",
        "UV_OFFLINE": "1",
        "UV_PYTHON_DOWNLOADS": "never",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_OPTIONAL_LOCKS": "0",
        "TMPDIR": str(work_root / "tmp" / "native_sync"),
        "UV_PROJECT_ENVIRONMENT": str(target_venv),
    }


def _bound_file(path: Path, *, semantic_sha256: str | None = None) -> dict[str, object]:
    raw = path.read_bytes()
    result: dict[str, object] = {
        "path": str(path),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "size_bytes": len(raw),
    }
    if semantic_sha256 is not None:
        result["semantic_sha256"] = semantic_sha256
    return result


def _native_log_case(
    tmp_path: Path,
    *,
    mutate: Callable[[dict[str, Any]], None] | None = None,
    mutate_framed: Callable[[bytes], bytes] | None = None,
) -> dict[str, Any]:
    bundle = tmp_path / "bundle"
    bundle.mkdir(mode=0o700)
    work = tmp_path / "work"
    work.mkdir(mode=0o700)
    target_venv = work / "native_venv"
    session_path = bundle / "00_session.json"
    session_payload = {"version": "myquant.v17.v2.phase0-session.v2", "session_id": "s1"}
    session_path.write_bytes(subject._canonical_bytes(session_payload) + b"\n")
    session_path.chmod(0o600)
    producer_path = tmp_path / "producer.py"
    producer_path.write_bytes(b"#!/usr/bin/env python3\n")
    producer_path.chmod(0o700)
    stdout = b"Resolved 91 packages\n"
    stderr = b""
    framed = struct.pack(">Q", len(stdout)) + stdout + struct.pack(">Q", len(stderr)) + stderr
    source = _source()
    toolchain = _toolchain()
    protected = subject._sample_protected_roots()
    command = {
        "ordinal": 1,
        "argv": [
            subject.UV_PATH,
            "sync",
            "--python",
            subject.BASE_PYTHON_PATH,
            "--locked",
            "--all-extras",
            "--offline",
        ],
        "cwd": str(ROOT),
        "environment": _native_environment(work, target_venv),
        "exit_code": 0,
        "signal": None,
        "tool_version": subject.UV_VERSION_OUTPUT,
        "stdout_offset_bytes": 8,
        "stdout_size_bytes": len(stdout),
        "stdout_sha256": hashlib.sha256(stdout).hexdigest(),
        "stderr_offset_bytes": 8 + len(stdout) + 8,
        "stderr_size_bytes": len(stderr),
        "stderr_sha256": hashlib.sha256(stderr).hexdigest(),
    }
    session_binding = _bound_file(session_path, semantic_sha256=SHA)
    session_binding["session_id"] = "s1"
    receipt: dict[str, Any] = {
        "version": subject.COMMAND_RECEIPT_VERSION,
        "protocol_version": subject.PROTOCOL_VERSION,
        "session_binding": session_binding,
        "step": {
            "ordinal": 1,
            "role": "native_sync_log",
            "kind": "log",
            "filename": "10_native_sync.log",
        },
        "producer": {
            **_bound_file(producer_path),
            "version": "myquant.v17.v2.phase0-session-runner.v1",
        },
        "source_before": copy.deepcopy(source),
        "source_after": copy.deepcopy(source),
        "toolchain_before": copy.deepcopy(toolchain),
        "toolchain_after": copy.deepcopy(toolchain),
        "package_source_superset_before": {"row_count": 1, "sha256": SHA},
        "package_source_superset_after": {"row_count": 1, "sha256": SHA},
        "protected_roots_before": copy.deepcopy(protected),
        "protected_roots_after": copy.deepcopy(protected),
        "limitations": list(subject.NORMATIVE_LIMITATIONS),
        "outcome": "PASSED",
        "failure_codes": [],
        "commands": [command],
        "claims": {"exit_code": 0},
        "framing": subject.COMMAND_FRAMING,
        "output_sha256": hashlib.sha256(framed).hexdigest(),
        "output_size_bytes": len(framed),
    }
    if mutate is not None:
        mutate(receipt)
    receipt["semantic_sha256"] = hashlib.sha256(subject._canonical_bytes(receipt)).hexdigest()
    if mutate_framed is not None:
        framed = mutate_framed(framed)
    log_path = bundle / "10_native_sync.log"
    log_path.write_bytes(
        subject.COMMAND_RECEIPT_PREFIX + subject._canonical_bytes(receipt) + b"\n" + framed
    )
    log_path.chmod(0o600)
    return {
        "path": log_path,
        "work": work,
        "target_venv": target_venv,
        "source": source,
        "toolchain": toolchain,
        "protected": protected,
        "receipt": receipt,
    }


def _parse_case(case: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    return subject._parse_native_sync_log(
        case["path"],
        repo_root=ROOT,
        work_root=case["work"],
        target_venv=case["target_venv"],
        source=case["source"],
        toolchain=case["toolchain"],
        protected_roots=case["protected"],
    )


def _valid_report(tmp_path: Path) -> dict[str, Any]:
    command = {
        "ordinal": 1,
        "argv": [
            subject.UV_PATH,
            "sync",
            "--python",
            subject.BASE_PYTHON_PATH,
            "--locked",
            "--all-extras",
            "--offline",
        ],
        "cwd": str(ROOT),
        "environment": _native_environment(tmp_path / "work", tmp_path / "work" / "native_venv"),
        "exit_code": 0,
        "signal": None,
        "tool_version": subject.UV_VERSION_OUTPUT,
        "stdout_offset_bytes": 8,
        "stdout_size_bytes": 0,
        "stdout_sha256": hashlib.sha256(b"").hexdigest(),
        "stderr_offset_bytes": 16,
        "stderr_size_bytes": 0,
        "stderr_sha256": hashlib.sha256(b"").hexdigest(),
    }
    directory = {
        "path": str(tmp_path),
        "mode": "0700",
        "st_uid": os.getuid(),
        "st_dev": 1,
        "st_ino": 2,
    }
    file_binding = {
        "path": str(tmp_path / "input"),
        "sha256": SHA,
        "size": 0,
        "mode": "0600",
    }
    installed = _metadata_record("quant-investor", "17.0.0")
    report: dict[str, Any] = {
        "schema_version": subject.SCHEMA_VERSION,
        "status": "THIRD_PARTY_NATIVE_ENVIRONMENT_ACCEPTED",
        "accepted": True,
        "dependency_environment_accepted": True,
        "native_dependency_environment_accepted": True,
        "complete_wheelhouse": True,
        "offline_only": True,
        "network_actions_performed": False,
        "repackaged_artifacts": False,
        "session_binding": {
            "session_id": "s1",
            "path": str(tmp_path / "00_session.json"),
            "sha256": SHA,
            "size_bytes": 1,
            "semantic_sha256": SHA,
        },
        "step": {
            "ordinal": 2,
            "role": "native_sync_receipt",
            "kind": "artifact",
            "filename": "20_native_dependency.json",
        },
        "producer": {
            "path": str(SCRIPT),
            "version": subject.SCHEMA_VERSION,
            "sha256": SHA,
            "size_bytes": 1,
        },
        "native_sync_log": {
            "path": str(tmp_path / "10_native_sync.log"),
            "sha256": SHA,
            "size_bytes": 1,
            "mode": "0600",
            "receipt_version": subject.COMMAND_RECEIPT_VERSION,
            "receipt_semantic_sha256": SHA,
            "framed_output_sha256": SHA,
            "framed_output_size_bytes": 0,
            "outcome": "PASSED",
        },
        "source": _source(),
        "toolchain": _toolchain(),
        "package_source_superset": {"row_count": 1, "sha256": SHA},
        "protected_roots": subject._sample_protected_roots(),
        "limitations": list(subject.NORMATIVE_LIMITATIONS),
        "scope": {
            "kind": "third_party_dependency_environment_only",
            "local_project_identity_checked_for_environment_exactness": True,
            "local_project_artifact_provenance_verified": False,
            "local_project_wheel_sdist_source_state_release_binding": (
                "OUTSIDE_SCOPE_SEPARATE_LOCAL_ARTIFACT_GATE_REQUIRED"
            ),
            "release_readiness_proven_by_this_report": False,
        },
        "inputs": {
            "pyproject": copy.deepcopy(file_binding),
            "uv_lock": copy.deepcopy(file_binding),
            "frozen_no_hash_export": copy.deepcopy(file_binding),
            "wheelhouse": {**directory, "owner_private": True},
            "work_root": copy.deepcopy(directory),
            "bundle_root": copy.deepcopy(directory),
        },
        "runtime": {
            "target_venv": {
                "path": str(tmp_path / "work" / "native_venv"),
                "pyvenv_cfg": copy.deepcopy(file_binding),
                "python_entrypoint": str(tmp_path / "work" / "native_venv" / "bin" / "python"),
                "python_entrypoint_symlink_target": subject.BASE_PYTHON_PATH,
                "python_entrypoint_lstat": {"mode": "0777", "st_dev": 1, "st_ino": 2},
                "resolved_base_python": {
                    "path": subject.BASE_PYTHON_PATH,
                    "sha256": subject.BASE_PYTHON_SHA256,
                    "size": subject.BASE_PYTHON_SIZE,
                    "mode": "0755",
                    "executable": True,
                },
            },
            "python": {
                "executable": str(tmp_path / "work" / "native_venv" / "bin" / "python"),
                "version": "3.13.7 (main)",
                "version_info": [3, 13, 7],
                "implementation": "cpython",
                "prefix": str(tmp_path / "work" / "native_venv"),
                "base_prefix": str(Path(subject.BASE_PYTHON_PATH).parents[1]),
            },
            "platform": {
                "machine": "arm64",
                "platform": "macOS",
                "system": "Darwin",
                "release": "25",
            },
            "marker_environment": {"python_version": "3.13"},
            "supported_tags_sha256": SHA,
            "supported_tag_count": 1,
        },
        "native_sync": {
            "receipt_version": subject.COMMAND_RECEIPT_VERSION,
            "receipt_semantic_sha256": SHA,
            "receipt_step": {
                "ordinal": 1,
                "role": "native_sync_log",
                "kind": "log",
                "filename": "10_native_sync.log",
            },
            "command": command,
            "outcome": "PASSED",
            "claims": {"exit_code": 0},
            "validated": True,
        },
        "local_project_identity_for_environment_reconciliation": {
            "name": "quant-investor",
            "version": "17.0.0",
        },
        "expected_dependencies": [],
        "inactive_marker_dependencies": [],
        "lock_reconciliation": {
            "expected_count": 1,
            "observed_count": 1,
            "malformed_count": 0,
            "local_project": {
                "name": "quant-investor",
                "version": "17.0.0",
                "count": 1,
            },
            "missing": [],
            "extra": [],
            "duplicates": [],
            "exact_match": True,
        },
        "installed_reconciliation": {
            "expected_count": 1,
            "third_party_expected_count": 0,
            "installed_count": 1,
            "local_project_identity_only": {
                "name": "quant-investor",
                "version": "17.0.0",
                "artifact_provenance_verified": False,
            },
            "installed": [
                {
                    **installed,
                    "name": "quant-investor",
                    "display_name": "quant-investor",
                }
            ],
            "missing": [],
            "extra": [],
            "version_mismatch": [],
            "exact_match": True,
        },
        "pip_absence": {
            "export_absent": True,
            "lock_absent": True,
            "installed_distribution_absent": True,
            "find_spec_none": True,
            "site_package_paths": [str(tmp_path / "site-packages")],
            "site_package_matches": [],
            "bin_matches": [],
            "accepted": True,
        },
        "artifact_evidence": {
            "expected_artifact_count": 0,
            "evidenced_artifact_count": 0,
            "complete_raw_artifact_count": 0,
            "wheelhouse_raw_artifact_count": 0,
            "complete_raw_artifacts": True,
            "complete_wheelhouse": True,
            "pip_http_cache_used": False,
            "materialization_performed": False,
            "records": [],
            "missing": [],
            "invalid": [],
        },
        "expected_raw_artifact_count": 0,
        "complete_raw_artifact_count": 0,
        "wheelhouse_raw_artifact_count": 0,
        "missing": [],
        "invalid": [],
        "failure_reasons": {
            "native_sync_receipt_invalid": False,
            "lock_reconciliation_mismatch": False,
            "installed_environment_mismatch": False,
            "native_pip_present": False,
            "invalid_artifact_evidence": False,
        },
    }
    report["semantic_sha256"] = hashlib.sha256(subject._canonical_bytes(report)).hexdigest()
    return report


def _rehash(report: dict[str, Any]) -> None:
    report.pop("semantic_sha256", None)
    report["semantic_sha256"] = hashlib.sha256(subject._canonical_bytes(report)).hexdigest()


def test_schema_is_closed_draft_2020_12_and_validates_exact_v2(
    tmp_path: Path,
) -> None:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    preflight_packaged_schema(schema)
    report = _valid_report(tmp_path)
    validate_instance_against_schema(report, schema)
    subject._validate_evidence_v2(report)
    downgraded = copy.deepcopy(report)
    downgraded["schema_version"] = "v17_third_party_dependency_environment_evidence.v1"
    _rehash(downgraded)
    with pytest.raises(SchemaValidationError):
        validate_instance_against_schema(downgraded, schema)
    with pytest.raises(subject.EvidenceError, match="downgrade"):
        subject._validate_evidence_v2(downgraded)


@pytest.mark.parametrize(
    "mutator,match",
    [
        (lambda value: value.__setitem__("extra", True), "keys mismatch"),
        (
            lambda value: value.__setitem__("accepted", False),
            "acceptance semantics mismatch",
        ),
        (
            lambda value: value["artifact_evidence"].__setitem__("materialization_performed", True),
            "artifact projection mismatch",
        ),
        (
            lambda value: value["lock_reconciliation"].__setitem__("expected_count", False),
            "must be an integer",
        ),
    ],
)
def test_exact_v2_semantics_reject_tampering(
    tmp_path: Path,
    mutator: Callable[[dict[str, Any]], None],
    match: str,
) -> None:
    report = _valid_report(tmp_path)
    mutator(report)
    _rehash(report)
    with pytest.raises(subject.EvidenceError, match=match):
        subject._validate_evidence_v2(report)


def test_native_command_v2_log_is_authoritative_and_fully_bound(
    tmp_path: Path,
) -> None:
    case = _native_log_case(tmp_path)
    receipt, projection = _parse_case(case)
    assert receipt["version"] == subject.COMMAND_RECEIPT_VERSION
    assert projection["outcome"] == "PASSED"
    assert projection["sha256"] == hashlib.sha256(case["path"].read_bytes()).hexdigest()
    assert projection["framed_output_sha256"] == receipt["output_sha256"]


@pytest.mark.parametrize(
    "mutator,match",
    [
        (
            lambda value: value.__setitem__("version", "myquant.v17.v2.phase0-command-receipt.v1"),
            "v1/downgrade",
        ),
        (lambda value: value.__setitem__("extra", True), "keys mismatch"),
        (lambda value: value.__setitem__("outcome", "FAILED"), "not successful"),
        (
            lambda value: value["commands"][0].__setitem__("exit_code", False),
            "must be an integer",
        ),
        (
            lambda value: value["commands"][0]["environment"].__setitem__("HOME", "/Users/maxwell"),
            "command semantics mismatch",
        ),
        (
            lambda value: value["toolchain_after"]["uv"].__setitem__("sha256", SHA),
            "uv identity mismatch",
        ),
        (
            lambda value: value["toolchain_after"]["pip_scope"].__setitem__(
                "native_pip_absent", False
            ),
            "pip_scope mismatch",
        ),
        (
            lambda value: value.__setitem__(
                "protected_roots_after",
                list(reversed(value["protected_roots_after"])),
            ),
            "identity/order mismatch",
        ),
    ],
)
def test_native_command_v2_rejects_downgrade_or_semantic_tampering(
    tmp_path: Path,
    mutator: Callable[[dict[str, Any]], None],
    match: str,
) -> None:
    case = _native_log_case(tmp_path, mutate=mutator)
    with pytest.raises(subject.EvidenceError, match=match):
        _parse_case(case)


def test_native_command_v2_rejects_framed_output_tampering(tmp_path: Path) -> None:
    case = _native_log_case(tmp_path, mutate_framed=lambda raw: raw + b"x")
    with pytest.raises(subject.EvidenceError, match="framed output binding mismatch"):
        _parse_case(case)


def test_frozen_export_evaluates_markers_and_pip_absence_is_explicit() -> None:
    raw = _export(
        'demo==1.0 ; python_version >= "3.13"',
        'legacy==2.0 ; python_version < "3.13"',
    )
    marker = {"python_version": "3.13"}
    active, inactive = subject._parse_frozen_export(raw, marker)
    assert [item["name"] for item in active] == ["demo"]
    result = subject._pip_absence(
        active=active,
        inactive=inactive,
        lock_packages=[{"name": "demo", "version": "1.0"}],
        installed=[_metadata_record("demo", "1.0")],
        probe={
            "pip_probe": {
                "find_spec_is_none": True,
                "site_package_paths": ["/private/site-packages"],
                "site_package_matches": [],
                "bin_matches": [],
            }
        },
    )
    assert result["accepted"] is True


@pytest.mark.parametrize("surface", ["export", "lock", "installed", "find_spec", "site", "bin"])
def test_native_pip_presence_is_rejected_on_every_surface(surface: str) -> None:
    active: list[dict[str, str]] = [{"name": "demo", "version": "1.0", "marker": ""}]
    lock: list[dict[str, object]] = [{"name": "demo", "version": "1.0"}]
    installed: list[dict[str, object]] = [_metadata_record("demo", "1.0")]
    probe = {
        "pip_probe": {
            "find_spec_is_none": True,
            "site_package_paths": ["/private/site-packages"],
            "site_package_matches": [],
            "bin_matches": [],
        }
    }
    if surface == "export":
        active.append({"name": "pip", "version": "25.2", "marker": ""})
    elif surface == "lock":
        lock.append({"name": "pip", "version": "25.2"})
    elif surface == "installed":
        installed.append(_metadata_record("pip", "25.2"))
    elif surface == "find_spec":
        probe["pip_probe"]["find_spec_is_none"] = False
    elif surface == "site":
        probe["pip_probe"]["site_package_matches"] = ["/private/site-packages/pip"]
    else:
        probe["pip_probe"]["bin_matches"] = ["/private/bin/pip3"]
    result = subject._pip_absence(
        active=active,
        inactive=[],
        lock_packages=lock,
        installed=installed,
        probe=probe,
    )
    assert result["accepted"] is False


def test_exact_lock_and_local_reconciliation_rejects_duplicates_and_extra() -> None:
    project = {"name": "quant-investor", "version": "17.0.0"}
    exact = subject._reconcile_lock(
        [{"name": "demo", "version": "1.0"}],
        project,
        [
            {"name": "demo", "version": "1.0"},
            {"name": "quant-investor", "version": "17.0.0"},
        ],
    )
    assert exact["exact_match"] is True
    bad = subject._reconcile_lock(
        [{"name": "demo", "version": "1.0"}],
        project,
        [
            {"name": "demo", "version": "1.0"},
            {"name": "demo", "version": "1.0"},
            {"name": "quant-investor", "version": "17.0.0"},
            {"name": "extra", "version": "2.0"},
        ],
    )
    assert bad["exact_match"] is False
    assert bad["duplicates"][0]["name"] == "demo"
    assert bad["extra"][0]["name"] == "extra"


def test_incomplete_wheelhouse_passes_only_behind_successful_native_receipt() -> None:
    incomplete = {
        "complete_wheelhouse": False,
        "missing": [{"name": "demo"}],
        "invalid": [],
    }
    accepted = subject._assess_dependency_environment(
        native_sync_receipt_valid=True,
        lock_reconciliation={"exact_match": True},
        reconciliation={"exact_match": True},
        pip_absence={"accepted": True},
        artifacts=incomplete,
    )
    assert accepted["accepted"] is True
    assert accepted["complete_wheelhouse"] is False
    no_receipt = subject._assess_dependency_environment(
        native_sync_receipt_valid=False,
        lock_reconciliation={"exact_match": True},
        reconciliation={"exact_match": True},
        pip_absence={"accepted": True},
        artifacts={**incomplete, "complete_wheelhouse": True},
    )
    assert no_receipt["accepted"] is False
    invalid = subject._assess_dependency_environment(
        native_sync_receipt_valid=True,
        lock_reconciliation={"exact_match": True},
        reconciliation={"exact_match": True},
        pip_absence={"accepted": True},
        artifacts={**incomplete, "invalid": [{"reason": "bad"}]},
    )
    assert invalid["accepted"] is False


def test_retained_wheelhouse_is_read_only_and_invalid_mode_blocks(
    tmp_path: Path,
) -> None:
    raw = b"wheel"
    filename = "demo-1.0-py3-none-any.whl"
    selected = _selected(filename, raw, tags=["py3-none-any"])
    package = {
        "name": "demo",
        "version": "1.0",
        "source": {"registry": "https://pypi.org/simple"},
        "wheels": [
            {
                "url": selected["url"],
                "hash": f"sha256:{selected['sha256']}",
                "size": selected["size"],
            }
        ],
    }
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir(mode=0o700)
    artifact = wheelhouse / filename
    artifact.write_bytes(raw)
    artifact.chmod(0o644)
    evidence = subject._artifact_evidence(
        expected_dependencies=[{"name": "demo", "version": "1.0"}],
        lock_packages=[package],
        supported_tags=["py3-none-any"],
        wheelhouse=wheelhouse,
    )
    assert evidence["invalid"][0]["reason"] == "wheelhouse_artifact_mode_invalid"
    assert evidence["pip_http_cache_used"] is False
    assert evidence["materialization_performed"] is False


def test_exact_cpython_3137_entrypoint_and_uv_identity_are_enforced(
    tmp_path: Path,
) -> None:
    venv = tmp_path / "native_venv"
    (venv / "bin").mkdir(parents=True)
    target = venv / "bin" / "python"
    target.symlink_to(subject.BASE_PYTHON_PATH)
    (venv / "pyvenv.cfg").write_text("home = frozen\n", encoding="utf-8")
    probe = {
        "python": {
            "executable": str(target),
            "version": "3.13.7 (main)",
            "version_info": [3, 13, 7],
            "implementation": "cpython",
            "prefix": str(venv),
            "base_prefix": str(Path(subject.BASE_PYTHON_PATH).parents[1]),
        }
    }
    binding = subject._validate_target_venv(venv, target, probe)
    assert binding["resolved_base_python"]["sha256"] == subject.BASE_PYTHON_SHA256
    wrong = copy.deepcopy(probe)
    wrong["python"]["version_info"] = [3, 13, 6]
    with pytest.raises(subject.EvidenceError, match="exact CPython 3.13.7"):
        subject._validate_target_venv(venv, target, wrong)
    uv = subject._uv_binding(subject.UV_PATH, cwd=ROOT)
    assert uv["version_output"] == subject.UV_VERSION_OUTPUT


def test_legacy_status_and_materialization_cli_are_rejected() -> None:
    base = [
        "--repo-root",
        str(ROOT),
        "--frozen-export",
        "/private/export",
        "--target-venv",
        "/private/work/native_venv",
        "--target-python",
        "/private/work/native_venv/bin/python",
        "--work-root",
        "/private/work",
        "--wheelhouse",
        "/private/work/wheelhouse",
        "--uv-cache",
        subject.UV_CACHE_PATH,
        "--uv-binary",
        subject.UV_PATH,
        "--native-sync-log",
        "/private/bundle/10_native_sync.log",
        "--output-json",
        "/private/bundle/20_native_dependency.json",
    ]
    with pytest.raises(SystemExit):
        subject.parse_args([*base, "--native-uv-sync-status", "PASSED"])
    with pytest.raises(SystemExit):
        subject.parse_args([*base, "--materialize-wheelhouse"])
    with pytest.raises(SystemExit):
        subject.parse_args([*base, "--pip-http-cache", "/private/pip"])


def test_pip_cache_and_materialization_helpers_fail_closed(tmp_path: Path) -> None:
    with pytest.raises(subject.EvidenceError, match="forbidden"):
        subject._scan_pip_http_cache(tmp_path, [])
    with pytest.raises(subject.EvidenceError, match="forbidden"):
        subject._materialize_raw_artifact_exact_once(
            source=tmp_path / "source",
            destination=tmp_path / "destination",
            selected={},
        )


def test_private_json_is_exact_once_and_never_overwrites(tmp_path: Path) -> None:
    parent = tmp_path / "bundle"
    parent.mkdir(mode=0o700)
    output = parent / "evidence.json"
    subject._write_private_json(output, {"a": 1})
    assert output.read_bytes() == b'{"a":1}\n'
    assert stat.S_IMODE(output.stat().st_mode) == 0o600
    with pytest.raises(subject.EvidenceError, match="refuses overwrite"):
        subject._write_private_json(output, {"a": 2})
    assert output.read_bytes() == b'{"a":1}\n'


def test_private_json_rejects_orphaned_stage(tmp_path: Path) -> None:
    parent = tmp_path / "bundle"
    parent.mkdir(mode=0o700)
    output = parent / "evidence.json"
    orphan = parent / ".evidence.json.stale.tmp"
    orphan.write_bytes(b"retained")
    orphan.chmod(0o600)
    with pytest.raises(subject.EvidenceError, match="orphaned staged output"):
        subject._write_private_json(output, {"a": 1})
    assert not output.exists()
    assert orphan.read_bytes() == b"retained"


def test_private_json_detects_parent_swap_and_retains_evidence(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    parent = tmp_path / "bundle"
    parent.mkdir(mode=0o700)
    moved = tmp_path / "bundle-moved"
    output = parent / "evidence.json"
    real_link = os.link
    swapped = False

    def swapping_link(*args: Any, **kwargs: Any) -> None:
        nonlocal swapped
        if not swapped:
            parent.rename(moved)
            parent.mkdir(mode=0o700)
            swapped = True
        real_link(*args, **kwargs)

    monkeypatch.setattr(subject.os, "link", swapping_link)
    with pytest.raises(subject.EvidenceError, match="parent path changed"):
        subject._write_private_json(output, {"a": 1})
    assert not output.exists()
    assert (moved / "evidence.json").exists()
    assert list(moved.glob(".evidence.json.*.tmp"))


def test_source_state_disables_textconv_and_binds_untracked_bytes(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(("git", "init", "-q"), cwd=repo, check=True)
    subprocess.run(("git", "config", "user.email", "test@example.invalid"), cwd=repo, check=True)
    subprocess.run(("git", "config", "user.name", "Test"), cwd=repo, check=True)
    tracked = repo / "tracked.txt"
    tracked.write_text("base\n", encoding="utf-8")
    subprocess.run(("git", "add", "tracked.txt"), cwd=repo, check=True)
    subprocess.run(("git", "commit", "-qm", "base"), cwd=repo, check=True)
    tracked.write_text("changed\n", encoding="utf-8")
    untracked = repo / "untracked.bin"
    untracked.write_bytes(b"\x00candidate")
    snapshot = subject._git_snapshot(repo.resolve())
    public = subject._public_source_state(snapshot)
    assert public["binary_diff_from_head"]["size"] > 0
    assert public["untracked"][0]["sha256"] == hashlib.sha256(b"\x00candidate").hexdigest()
    binding = subject._command_source_binding(snapshot)
    assert binding["source_state_sha256"] == public["source_state_sha256"]


def test_canonical_command_source_binding_matches_evidence_index() -> None:
    index_path = ROOT / "scripts" / "v17_phase0_evidence_index.py"
    spec = importlib.util.spec_from_file_location("dependency_index_contract_test", index_path)
    assert spec is not None and spec.loader is not None
    index = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(index)
    base_commit = (
        subprocess.run(
            ("git", "rev-parse", "--verify", "HEAD"),
            cwd=ROOT,
            check=True,
            stdout=subprocess.PIPE,
        )
        .stdout.decode("ascii")
        .strip()
    )
    snapshot = index._git_snapshot(ROOT, base_commit)
    expected = index._source_binding_from_state(index._public_source_state(snapshot))
    assert subject._canonical_command_source_binding(ROOT) == expected
